id: PD69660D1
initial_creation_type: input
source_metadata:
  title: Āryaśūra Series
  language: bo
  description: Texts by the great Indian master Āryaśūra, known to Tibetans as Lobpon
    Pawo (slob dpon dpa' bo), author of the famous Garland of Birth Stories (Jātakamālā)
  volume:
    f805510f7ca245ab8060c034408bf918:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    3127b3e638d44cb791467cae2a68e397:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T02:08:51.636425'
last_modified_at: '2022-03-01T02:08:51.636428'
statistics:
  total_words: 568
  total_non_words: 40
quality:
  non_words_ratio: 0.07
